name: Flutter CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Change to app directory
        run: cd app
      - name: Get dependencies
        run: flutter pub get
        working-directory: app
      - name: Analyze code
        run: flutter analyze .
        working-directory: app
      - name:  Build APK
        run: flutter build apk --split-per-abi
        working-directory: app