name: Flutter CI

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          cache: 'gradle'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'
      - name: Change to app directory
        run: cd app
      - name: Get dependencies
        run: flutter pub get
        working-directory: app
      - name: Analyze code
        run: flutter analyze .
        working-directory: app
      - name:  Build APK
        run: flutter build apk --split-per-abi
        working-directory: app
      - uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: ./app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
      - name: Internal Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          makeLatest: true
          allowUpdates: true
          removeArtifacts: true
          generateReleaseNotes: false
          artifacts: "./app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk"